import * as ppt from "../lib/playwright"

let page = null
let done = null

beforeAll(async () => {
	jest.setTimeout(600e3)
	const browserStr = process.env.BROWSER
	;[page, done] = await ppt.openPage(browserStr, "http://localhost:3000/demo")
})

afterAll(async () => {
	await done()
})

beforeEach(async () => {
	await page.focus("#editor")
	await page.clear()
})

test("can type and backspace words", async () => {
	await page.type("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	let data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! ")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, ")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\n")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! ")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, ")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\n")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! ")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, ")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello")
	await page.backspaceWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("")
})

test("can type and delete words", async () => {
	await page.type("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	let data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await page.left(52)
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(", world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(" world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(" 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("\n\nHello, world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("\nHello, world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(", world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(" world! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("! 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(" 😀\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("\n\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("\nHello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("Hello, world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(", world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(" world! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("! 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe(" 😀")
	await page.deleteWord()
	data = await page.getCodex("#editor")
	expect(data).toBe("")
})
